//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Espacio.cs
//  @ Date : 14/08/2019
//  @ Author : 
//
//


namespace Entidades del Dominio{
	public class Espacio {
		private int tamañoM2 ;
		private String identificador ;
		private String ubicación ;
		private boolean tipoEspecial ;
		private boolean espacioLibre ;
		private String descripción ;
		public void OcuparEspacio(String tamaño, boolean TipoEspecial){
		}
		public boolean EspacioDisponible(){
		}
		public boolean VerificarEspacio(String identificador){
		}
		public int getTamaño(){
		}
		public String getIdentificador(){
		}
		public String getUbicación(){
		}
		public boolean getTipoEspacioLibre(){
		}
		public String getDescripción(){
		}
	}
}
