//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionUsuarios.cs
//  @ Date : 14/08/2019
//  @ Author : 
//
//


namespace Logica del Negocio{
	public class GestionUsuarios {
		public usuario Usuario ;
		public void agregarUsuario(Usuario Usuario){
		}
		public void borrarUsuario(cedula int){
		}
	}
}
