//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Gestion Vehiculo.cs
//  @ Date : 14/08/2019
//  @ Author : 
//
//


namespace Logica del Negocio{
	public class Gestion Vehiculo {
		public vehiculo Vehiculo ;
		public void adicionarVehiculo(){
		}
		public void consultarVehiculo(){
		}
	}
}
