//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionarVigilante.cs
//  @ Date : 14/08/2019
//  @ Author : 
//
//


namespace Logica del Negocio{
	public class GestionarVigilante {
		public vigilante agregarVigilante(){
		}
		public vigilante eliminarVigilante(){
		}
		public vigilante modificarVigilnte(){
		}
		public vigilante buscarVigilante(){
		}
	}
}
