//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionarAsignacionDeEspacios.cs
//  @ Date : 14/08/2019
//  @ Author : 
//
//


namespace Logica del Negocio{
	public class GestionarAsignacionDeEspacios {
		public boolean OcuparEspacios(String identificador){
		}
		public boolean liberarEspacio(String identificador){
		}
		public boolean VerificarEspacio(String identificador, Date calendar){
		}
	}
}
