//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.cs
//  @ Date : 14/08/2019
//  @ Author : 
//
//


namespace Entidades del Dominio{
	public class Usuario {
		public object id ;
		public int cedula ;
		public string nombre ;
		public int celular ;
		public boolean genero ;
		public date fecha_cumple ;
	}
}
