//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Vehiculo.cs
//  @ Date : 14/08/2019
//  @ Author : 
//
//


namespace Entidades del Dominio{
	public class Vehiculo {
		public int id ;
		public string placa ;
		public string propietario ;
		public string telefono ;
		public string marca ;
		public string color ;
		public string modelo ;
		public string motor ;
		public String getPlaca(){
		}
	}
}
