//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Vigilantes.cs
//  @ Date : 14/08/2019
//  @ Author : 
//
//


namespace Entidades del Dominio{
	public class Vigilantes {
		public int cedula ;
		public String nombre ;
		public String apellidos ;
		public int telefono ;
		public String correo ;
	}
}
